### ISSUE TITLE
Difference?

### ISSUE THREAD

**Issue by myinnos** [steelkiwi/cropiwa#1]
How it is difference from [uCrop](https://github.com/Yalantis/uCrop) and What is the library size?

**Comment by polyak01** [comment]
Good day to you, @myinnos . That’s a good question!)

First of all, I’d like to point out that it is not entirely appropriate to compare these two libraries. uCrop is definitely one of the best libraries to crop images. I know some of its’ developers personally and I value their efforts. Also, if you go through the likes given to our library you will find some likes from uCrop contributors.

uCrop is developed as a box solution, i.e. it is integrated in a project like Activity. Of course, there is customization, but it is not as flexible , or you will have to take a deeper look at the source code by yourself. If you are OK with it and you don’t want to customize everything then it is a great solution.

CropIwa is developed to be a more flexible library.  You can add or delete all features nice and easy. There is long readme specially for this. Without any difficulties you can build a unique UI just with a few features. Just like here:

![Screenshot 1](https://github.com/steelkiwi/cropiwa/blob/master/assets/screen2.png)

### Let’s see what actually is in the library.
*  First of all, you can crop images into forms. It enables to crop not only in the regular square but in an oval form as well. And if it is not enough for you, then you can also create custom crop area shapes(
 a triangle, for instance,  and crop in it =) As far as your imagination takes you.). Just extend `CropIwaShape` (for an example refer to [CropIwaOvalShape](library/src/main/java/com/steelkiwi/cropiwa/shape/CropIwaOvalShape.java)) and set an instance of you class using:
```java
cropView.configureOverlay()
  .setCropShape(new MyAwesomeShape())
  .apply();
```
*  If you watch the gif file from readme till the end you can see that it is possible to crop with multi touch in Dynamic Overlay mode :)
* You can easily turn on and turn off Scale and translation
![Screenshot 2](https://github.com/steelkiwi/cropiwa/blob/master/assets/screen4.jpg)

* You can change the image quality. PNG, JPEG, WEBP formats are available. And if you want your crop to be the same style that your app is, you can make a flexible setting of Border, Corner, Overlay, Grid colors. Also you can switch off Grid rendering or make it Dashed, just like at this screenshot.
![Screenshot 3](https://github.com/steelkiwi/cropiwa/blob/master/assets/screen3.jpg)

### For further information go through [README](https://github.com/steelkiwi/cropiwa/blob/master/README.md) and download sample))) We will appreciate your suggestions and contribution to our project.

**Comment by myinnos** [comment]
**Great**! I will give a `try`!
