### ISSUE TITLE
Сохранение без поворота

### ISSUE THREAD

**Issue by vellrya** [steelkiwi/cropiwa#2]
Здравствуйте. Есть такой вопрос: если повернуть картинку во время обрезания, то при сохранении картинка повернута не будет. Насколько я понимаю, мы картинку и не поворачиваем, а поворачиваем CropiwaView. Есть ли удобный способ сохранения картинки с поворотом?

**Comment by polyak01** [comment]
@vellrya пока мы еще не интегрировали поворот. Видели ваше видео тут https://github.com/steelkiwi/cropiwa/issues/3 , как мы понимаем, вы вращаете полностью CropView. Когда появится время - мы обязательно интегрируем функцию переворота картинок. Сообщу об этом здесь.

Спасибо, что пользуетесь CropIwa )
