### ISSUE TITLE
Next Release 

### ISSUE THREAD

**Issue by sdoward** [steelkiwi/cropiwa#26]
I would love to get my hands on the changes in https://github.com/steelkiwi/cropiwa/pull/25

Do you have a release schedule?

**Comment by polyak01** [comment]
If it's urgent, I'll update the version in 4 hours.

**Comment by flasher297** [comment]
@polyak01 Thanks for merging my PR.
It would be cool to see updated version as soon as you have time,

**Comment by sdoward** [comment]
Well I am using [jitpack](https://jitpack.io/#steelkiwi/cropiwa) so I can manage whilst I develop. But it would be great to use an actual release artefact before I merge by changes.

**Comment by polyak01** [comment]
@flasher297 @sdoward Sorry for your waiting. Done!
```
compile 'com.steelkiwi:cropiwa:1.0.2'
```
Thanks for your contribution.
