### ISSUE TITLE
Small image can't scale

### ISSUE THREAD

**Issue by AnswerZhao** [steelkiwi/cropiwa#3]
When the loaded photo is too small , the image can't scale by touching.

**Comment by vellrya** [comment]
I confirm.
Video: http://dropmefiles.com/UEQjI
Scale and translation gesture are activated.

**Comment by polyak01** [comment]
* @vellrya @AnswerZhao You can set a min-max scale. Default min is [0.7](https://github.com/steelkiwi/cropiwa/blob/8d5114a7ef28ab36345e889866ba57b0cdcd9989/library/src/main/java/com/steelkiwi/cropiwa/config/CropIwaImageViewConfig.java#L19), default max is [3](https://github.com/steelkiwi/cropiwa/blob/8d5114a7ef28ab36345e889866ba57b0cdcd9989/library/src/main/java/com/steelkiwi/cropiwa/config/CropIwaImageViewConfig.java#L20).
```java
app:ci_max_scale="1f"

cropView.configureImage()
  .setMinScale(minScale)
  .setMaxScale(maxScale)
  .apply();
```

Try to decrease minScale / increase maxScale

**Comment by AnswerZhao** [comment]
@polyak01 It can't works.

**Comment by polyak01** [comment]
@AnswerZhao do you try to setMinScale(1f)?

**Comment by AnswerZhao** [comment]
@polyak01 
`float scaleFactor = detector.getScaleFactor();
 float newScale = matrixUtils.getScaleX(imageMatrix) * scaleFactor;`
When the photo is too small, the newScale value is too lager than the maxScale.(70*70Px, the newScale is 25), so i think the scale value is not perfect. I change the method isValidScal() to resolve it  finally.

**Comment by AnswerZhao** [comment]
@vellrya 9 is not work for everything, you can try a 43*43 picture.

**Comment by vellrya** [comment]
Okay. I decided for myself this problem. I completely removed Min and Maxscale and did this:
```
cropView.configureOverlay()
                .setAspectRatio(AspectRatio.IMG_SRC)
                .apply()
```
Now I can correctly move and enlarge small pictures. (http://dropmefiles.com/KQByj)
It remains only to wait for the ability to rotate pictures in this library)

**Comment by polyak01** [comment]
@AnswerZhao Did you solved the problem?

**Comment by AnswerZhao** [comment]
@polyak01 Yep. You can change the implement of the method isValidScal() ,or increase the maxScale, or remove the limits of  maxScale.
