### ISSUE TITLE
How to set the border size?

### ISSUE THREAD

**Issue by NicodeLee** [steelkiwi/cropiwa#4]
Thank for you job.
see：http://7xlc12.com1.z0.glb.clouddn.com/3D3F7617-1A48-444A-A101-2BA6CB25D832.png

**Comment by polyak01** [comment]
@NicodeLee 
* Dimensions.
```java
app:ci_border_width="1dp"
app:ci_corner_width="1dp"
app:ci_grid_width="1dp"

cropView.configureOverlay()
  .setBorderStrokeWidth(dps)
  .setCornerStrokeWidth(dps)
  .setGridStrokeWidth(dps)
  .apply();
```

**Comment by NicodeLee** [comment]
Sorry for my poor English.
My question is set the crop area by set she width and height.

**Comment by navdroid** [comment]
@NicodeLee Any success?
